export const BID_CREATE_REQUEST = "BID_CREATE_REQUEST";
export const BID_CREATE_SUCCESS = "BID_CREATE_SUCCESS";
export const BID_CREATE_FAIL = "BID_CREATE_FAIL";
export const BID_CREATE_RESET = "BID_CREATE_RESET";

export const BID_DETAILS_REQUEST = "BID_DETAILS_REQUEST";
export const BID_DETAILS_SUCCESS = "BID_DETAILS_SUCCESS";
export const BID_DETAILS_FAIL = "BID_DETAILS_FAIL";

export const BID_PAY_REQUEST = "BID_PAY_REQUEST";
export const BID_PAY_SUCCESS = "BID_PAY_SUCCESS";
export const BID_PAY_FAIL = "BID_PAY_FAIL";
export const BID_PAY_RESET = "BID_PAY_RESET";

export const BID_LIST_MY_REQUEST = "BID_LIST_MY_REQUEST";
export const BID_LIST_MY_SUCCESS = "BID_LIST_MY_SUCCESS";
export const BID_LIST_MY_FAIL = "BID_LIST_MY_FAIL";
export const BID_LIST_MY_RESET = "BID_LIST_MY_RESET";

export const BID_LAND_LIST_REQUEST = "BID_LAND_LIST_REQUEST";
export const BID_LAND_LIST_SUCCESS = "BID_LAND_LIST_SUCCESS";
export const BID_LAND_LIST_FAIL = "BID_LAND_LIST_FAIL";
export const BID_LAND_LIST_RESET = "BID_LAND_LIST_RESET";

export const BID_APPROVE_REQUEST = "BID_APPROVE_REQUEST";
export const BID_APPROVE_SUCCESS = "BID_APPROVE_SUCCESS";
export const BID_APPROVE_FAIL = "BID_APPROVE_FAIL";
export const BID_APPROVE_RESET = "BID_APPROVE_RESET";
