export const CONTRACT_CREATE_REQUEST = "CONTRACT_CREATE_REQUEST";
export const CONTRACT_CREATE_SUCCESS = "CONTRACT_CREATE_SUCCESS";
export const CONTRACT_CREATE_FAIL = "CONTRACT_CREATE_FAIL";
export const CONTRACT_CREATE_RESET = "CONTRACT_CREATE_RESET";

export const CONTRACT_DETAILS_REQUEST = "CONTRACT_DETAILS_REQUEST";
export const CONTRACT_DETAILS_SUCCESS = "CONTRACT_DETAILS_SUCCESS";
export const CONTRACT_DETAILS_FAIL = "CONTRACT_DETAILS_FAIL";

export const CONTRACT_LIST_CONTRACTOR_REQUEST =
  "CONTRACT_LIST_CONTRACTOR_REQUEST";
export const CONTRACT_LIST_CONTRACTOR_SUCCESS =
  "CONTRACT_LIST_CONTRACTOR_SUCCESS";
export const CONTRACT_LIST_CONTRACTOR_FAIL = "CONTRACT_LIST_CONTRACTOR_FAIL";
export const CONTRACT_LIST_CONTRACTOR_RESET = "CONTRACT_LIST_CONTRACTOR_RESET";

export const CONTRACT_LIST_FARMER_REQUEST = "CONTRACT_LIST_FARMER_REQUEST";
export const CONTRACT_LIST_FARMER_SUCCESS = "CONTRACT_LIST_FARMER_SUCCESS";
export const CONTRACT_LIST_FARMER_FAIL = "CONTRACT_LIST_FARMER_FAIL";
export const CONTRACT_LIST_FARMER_RESET = "CONTRACT_LIST_FARMER_RESET";

export const CONTRACT_LAND_LIST_REQUEST = "CONTRACT_LAND_LIST_REQUEST";
export const CONTRACT_LAND_LIST_SUCCESS = "CONTRACT_LAND_LIST_SUCCESS";
export const CONTRACT_LAND_LIST_FAIL = "CONTRACT_LAND_LIST_FAIL";
export const CONTRACT_LAND_LIST_RESET = "CONTRACT_LAND_LIST_RESET";

export const CONTRACT_SETTLE_REQUEST = "CONTRACT_SETTLE_REQUEST";
export const CONTRACT_SETTLE_SUCCESS = "CONTRACT_SETTLE_SUCCESS";
export const CONTRACT_SETTLE_FAIL = "CONTRACT_SETTLE_FAIL";
export const CONTRACT_SETTLE_RESET = "CONTRACT_SETTLE_RESET";
