export const MY_LANDS_LIST_REQUEST = "MY_LANDS_LIST_REQUEST";
export const MY_LANDS_LIST_SUCCESS = "MY_LANDS_LIST_SUCCESS";
export const MY_LANDS_LIST_FAIL = "MY_LANDS_LIST_FAIL";

export const LAND_DETAILS_REQUEST = "LAND_DETAILS_REQUEST";
export const LAND_DETAILS_SUCCESS = "LAND_DETAILS_SUCCESS";
export const LAND_DETAILS_FAIL = "LAND_DETAILS_FAIL";

export const LAND_DELETE_REQUEST = "LAND_DELETE_REQUEST";
export const LAND_DELETE_SUCCESS = "LAND_DELETE_SUCCESS";
export const LAND_DELETE_FAIL = "LAND_DELETE_FAIL";

export const LAND_CREATE_REQUEST = "LAND_CREATE_REQUEST";
export const LAND_CREATE_SUCCESS = "LAND_CREATE_SUCCESS";
export const LAND_CREATE_FAIL = "LAND_CREATE_FAIL";
export const LAND_CREATE_RESET = "LAND_CREATE_RESET";

export const LAND_UPDATE_REQUEST = "LAND_UPDATE_REQUEST";
export const LAND_UPDATE_SUCCESS = "LAND_UPDATE_SUCCESS";
export const LAND_UPDATE_FAIL = "LAND_UPDATE_FAIL";
export const LAND_UPDATE_RESET = "LAND_UPDATE_RESET";

export const ALL_LANDS_LIST_REQUEST = "ALL_LANDS_LIST_REQUEST";
export const ALL_LANDS_LIST_SUCCESS = "ALL_LANDS_LIST_SUCCESS";
export const ALL_LANDS_LIST_FAIL = "ALL_LANDS_LIST_FAIL";
