export const MY_PRODUCES_LIST_REQUEST = "MY_PRODUCES_LIST_REQUEST";
export const MY_PRODUCES_LIST_SUCCESS = "MY_PRODUCES_LIST_SUCCESS";
export const MY_PRODUCES_LIST_FAIL = "MY_PRODUCES_LIST_FAIL";

export const MY_PURCHASES_LIST_REQUEST = "MY_PURCHASES_LIST_REQUEST";
export const MY_PURCHASES_LIST_SUCCESS = "MY_PURCHASES_LIST_SUCCESS";
export const MY_PURCHASES_LIST_FAIL = "MY_PURCHASES_LIST_FAIL";
export const MY_PURCHASES_LIST_RESET = "MY_PURCHASES_LIST_RESET";

export const MY_SALES_LIST_REQUEST = "MY_SALES_LIST_REQUEST";
export const MY_SALES_LIST_SUCCESS = "MY_SALES_LIST_SUCCESS";
export const MY_SALES_LIST_FAIL = "MY_SALES_LIST_FAIL";
export const MY_SALES_LIST_RESET = "MY_SALES_LIST_RESET";

export const PRODUCE_DETAILS_REQUEST = "PRODUCE_DETAILS_REQUEST";
export const PRODUCE_DETAILS_SUCCESS = "PRODUCE_DETAILS_SUCCESS";
export const PRODUCE_DETAILS_FAIL = "PRODUCE_DETAILS_FAIL";
export const PRODUCE_DETAILS_RESET = "PRODUCE_DETAILS_RESET";

export const PRODUCE_DELETE_REQUEST = "PRODUCE_DELETE_REQUEST";
export const PRODUCE_DELETE_SUCCESS = "PRODUCE_DELETE_SUCCESS";
export const PRODUCE_DELETE_FAIL = "PRODUCE_DELETE_FAIL";

export const PRODUCE_CREATE_REQUEST = "PRODUCE_CREATE_REQUEST";
export const PRODUCE_CREATE_SUCCESS = "PRODUCE_CREATE_SUCCESS";
export const PRODUCE_CREATE_FAIL = "PRODUCE_CREATE_FAIL";
export const PRODUCE_CREATE_RESET = "PRODUCE_CREATE_RESET";

export const PRODUCE_UPDATE_REQUEST = "PRODUCE_UPDATE_REQUEST";
export const PRODUCE_UPDATE_SUCCESS = "PRODUCE_UPDATE_SUCCESS";
export const PRODUCE_UPDATE_FAIL = "PRODUCE_UPDATE_FAIL";
export const PRODUCE_UPDATE_RESET = "PRODUCE_UPDATE_RESET";

export const ALL_PRODUCES_LIST_REQUEST = "ALL_PRODUCES_LIST_REQUEST";
export const ALL_PRODUCES_LIST_SUCCESS = "ALL_PRODUCES_LIST_SUCCESS";
export const ALL_PRODUCES_LIST_FAIL = "ALL_PRODUCES_LIST_FAIL";

export const PRODUCE_PAY_REQUEST = "PRODUCE_PAY_REQUEST";
export const PRODUCE_PAY_SUCCESS = "PRODUCE_PAY_SUCCESS";
export const PRODUCE_PAY_FAIL = "PRODUCE_PAY_FAIL";
export const PRODUCE_PAY_RESET = "PRODUCE_PAY_RESET";

export const PRODUCE_DELIVER_REQUEST = "PRODUCE_DELIVER_REQUEST";
export const PRODUCE_DELIVER_SUCCESS = "PRODUCE_DELIVER_SUCCESS";
export const PRODUCE_DELIVER_FAIL = "PRODUCE_DELIVER_FAIL";
export const PRODUCE_DELIVER_RESET = "PRODUCE_DELIVER_RESET";
