export const states = [
  {
    name: "Sample state",
    code: "s",
    districts: ["Sample district"],
    seasons: [
      {
        name: "Sample season",
        crops: ["Sample crop"],
      },
    ],
  },
  {
    name: "Maharashtra",
    code: "mh",
    seasons: [
      {
        name: "Autumn",
        crops: ["Maize"],
      },
      {
        name: "Kharif",
        crops: [
          "Arhar/Tur",
          "Bajra",
          "Jowar",
          "Maize",
          "Rice",
          "Cotton(lint)",
          "Sesamum",
        ],
      },
      {
        name: "Rabi",
        crops: ["Jowar", "Maize", "Wheat", "Linseed", "Sesamum"],
      },
      {
        name: "Summer",
        crops: ["Maize", "Rice"],
      },
      {
        name: "Whole Year",
        crops: ["Cotton(lint)", "Onion"],
      },
    ],
    districts: [
      "AKOLA",
      "AMRAVATI",
      "AURANGABAD",
      "BEED",
      "BHANDARA",
      "BULDHANA",
      "CHANDRAPUR",
      "DHULE",
      "GADCHIROLI",
      "GONDIA",
      "HINGOLI",
      "JALGAON",
      "JALNA",
      "KOLHAPUR",
      "LATUR",
      "MUMBAI",
      "NAGPUR",
      "NANDED",
      "NANDURBAR",
      "NASHIK",
      "OSMANABAD",
      "PALGHAR",
      "PARBHANI",
      "PUNE",
      "RAIGAD",
      "RATNAGIRI",
      "SANGLI",
      "SATARA",
      "SINDHUDURG",
      "SOLAPUR",
      "THANE",
      "WARDHA",
      "WASHIM",
      "YAVATMAL",
    ],
  },
  {
    name: "Madhya Pradesh",
    code: "mp",
    seasons: [
      {
        name: "Kharif",
        crops: [
          "Arhar/Tur",
          "Bajra",
          "Jowar",
          "Maize",
          "Rice",
          "Cotton(lint)",
          "Sesamum",
        ],
      },
      {
        name: "Rabi",
        crops: ["Linseed", "Wheat", "Jowar"],
      },
      {
        name: "Whole Year ",
        crops: [
          "Garlic",
          "Onion",
          "Potato",
          "Sesamum",
          "Turmeric",
          "Arhar/Tur",
          "Bajra",
          "Cotton(lint)",
          "Linseed",
          "Maize",
          "Rice",
          "Wheat",
        ],
      },
    ],
    districts: [
      "AGAR MALWA",
      "ALIRAJPUR",
      "ANUPPUR",
      "ASHOKNAGAR",
      "BALAGHAT",
      "BARWANI",
      "BETUL",
      "BHIND",
      "BHOPAL",
      "BURHANPUR",
      "CHHATARPUR",
      "CHHINDWARA",
      "DAMOH",
      "DATIA",
      "DEWAS",
      "DHAR",
      "DINDORI",
      "GUNA",
      "GWALIOR",
      "HARDA",
      "HOSHANGABAD",
      "INDORE",
      "JABALPUR",
      "JHABUA",
      "KATNI",
      "KHANDWA",
      "KHARGONE",
      "MANDLA",
      "MANDSAUR",
      "MORENA",
      "NARSINGHPUR",
      "NEEMUCH",
      "PANNA",
      "RAISEN",
      "RAJGARH",
      "RATLAM",
      "REWA",
      "SAGAR",
      "SATNA",
      "SEHORE",
      "SEONI",
      "SHAHDOL",
      "SHAJAPUR",
      "SHEOPUR",
      "SHIVPURI",
      "SIDHI",
      "SINGRAULI",
      "TIKAMGARH",
      "UJJAIN",
      "UMARIA",
      "VIDISHA",
    ],
  },
  {
    name: "Punjab",
    code: "pb",
    seasons: [
      {
        name: "Kharif",
        crops: [
          "Arhar/Tur",
          "Bajra",
          "Maize",
          "Rice",
          "Sesamum",
          "Cotton(lint)",
          "Jowar",
        ],
      },
      {
        name: "Rabi",
        crops: ["Wheat", "Linseed"],
      },
      {
        name: "Whole Year",
        crops: ["Cotton(lint)"],
      },
    ],
    districts: [
      "AMRITSAR",
      "BARNALA",
      "BATHINDA",
      "FARIDKOT",
      "FATEHGARH SAHIB",
      "FAZILKA",
      "FIROZEPUR",
      "GURDASPUR",
      "HOSHIARPUR",
      "JALANDHAR",
      "KAPURTHALA",
      "LUDHIANA",
      "MANSA",
      "MOGA",
      "MUKTSAR",
      "NAWANSHAHR",
      "PATHANKOT",
      "PATIALA",
      "RUPNAGAR",
      "S.A.S NAGAR",
      "SANGRUR",
      "TARN TARAN",
    ],
  },
  {
    name: "Rajasthan",
    code: "rj",
    seasons: [
      {
        name: "Kharif",
        crops: [
          "Bajra",
          "Cotton(lint)",
          "Jowar",
          "Maize",
          "Onion",
          "Rice",
          "Sesamum",
          "Arhar/Tur",
        ],
      },
      {
        name: "Rabi",
        crops: ["Linseed", "Wheat"],
      },
      {
        name: "Whole Year",
        crops: ["Garlic", "Onion", "Potato", "Turmeric"],
      },
    ],
    districts: [
      "AJMER",
      "ALWAR",
      "BANSWARA",
      "BARAN",
      "BARMER",
      "BHARATPUR",
      "BHILWARA",
      "BIKANER",
      "BUNDI",
      "CHITTORGARH",
      "CHURU",
      "DAUSA",
      "DHOLPUR",
      "DUNGARPUR",
      "GANGANAGAR",
      "HANUMANGARH",
      "JAIPUR",
      "JAISALMER",
      "JALORE",
      "JHALAWAR",
      "JHUNJHUNU",
      "JODHPUR",
      "KARAULI",
      "KOTA",
      "NAGAUR",
      "PALI",
      "PRATAPGARH",
      "RAJSAMAND",
      "SAWAI MADHOPUR",
      "SIKAR",
      "SIROHI",
      "TONK",
      "UDAIPUR",
    ],
  },
  {
    name: "Uttar Pradesh",
    code: "up",
    seasons: [
      {
        name: "Kharif",
        crops: [
          "Arhar/Tur",
          "Bajra",
          "Jowar",
          "Maize",
          "Onion",
          "Rice",
          "Sesamum",
          "Cotton(lint)",
          "Ginger",
        ],
      },
      {
        name: "Rabi",
        crops: [
          "Wheat",
          "Linseed",
          "Maize",
          "Onion",
          "Potato",
          "Turmeric",
          "Garlic",
        ],
      },
      {
        name: "Summer",
        crops: ["Maize", "Onion", "Rice"],
      },
      {
        name: "Whole Year",
        crops: ["Potato", "Onion", "Garlic", "Turmeric"],
      },
    ],
    districts: [
      "AGRA",
      "ALIGARH",
      "ALLAHABAD",
      "AMBEDKAR NAGAR",
      "AMETHI",
      "AMROHA",
      "AURAIYA",
      "AZAMGARH",
      "BAGHPAT",
      "BAHRAICH",
      "BALLIA",
      "BALRAMPUR",
      "BANDA",
      "BARABANKI",
      "BAREILLY",
      "BASTI",
      "BIJNOR",
      "BUDAUN",
      "BULANDSHAHR",
      "CHANDAULI",
      "CHITRAKOOT",
      "DEORIA",
      "ETAH",
      "ETAWAH",
      "FAIZABAD",
      "FARRUKHABAD",
      "FATEHPUR",
      "FIROZABAD",
      "GAUTAM BUDDHA NAGAR",
      "GHAZIABAD",
      "GHAZIPUR",
      "GONDA",
      "GORAKHPUR",
      "HAMIRPUR",
      "HAPUR",
      "HARDOI",
      "HATHRAS",
      "JALAUN",
      "JAUNPUR",
      "JHANSI",
      "KANNAUJ",
      "KANPUR DEHAT",
      "KANPUR NAGAR",
      "KASGANJ",
      "KAUSHAMBI",
      "KHERI",
      "KUSHI NAGAR",
      "LALITPUR",
      "LUCKNOW",
      "MAHARAJGANJ",
      "MAHOBA",
      "MAINPURI",
      "MATHURA",
      "MAU",
      "MEERUT",
      "MIRZAPUR",
      "MORADABAD",
      "MUZAFFARNAGAR",
      "PILIBHIT",
      "PRATAPGARH",
      "RAE BARELI",
      "RAMPUR",
      "SAHARANPUR",
      "SAMBHAL",
      "SANT KABEER NAGAR",
      "SANT RAVIDAS NAGAR",
      "SHAHJAHANPUR",
      "SHAMLI",
      "SHRAVASTI",
      "SIDDHARTH NAGAR",
      "SITAPUR",
      "SONBHADRA",
      "SULTANPUR",
      "UNNAO",
      "VARANASI",
    ],
  },
];

export const STATE_TO_CODE = {
  Maharashtra: "mh",
  Rajasthan: "rj",
  Punjab: "pb",
  "Madhya Pradesh": "mp",
  "Uttar Pradesh": "up",
};
